name: AI Code Review
 
on:

  pull_request:

    types: [opened, synchronize, reopened]
 
jobs:

  review:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
 
      - name: Set up Python

        uses: actions/setup-python@v4

        with:

          python-version: '3.10'
 
      - name: Install dependencies

        run: pip install requests
 
      - name: Run AI code review

        run: python .github/scripts/review.py

      - name: Confirm API key is set
        run: echo "✅ API key was passed"
        env:
              OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}


 