name: AI Code Review
 
on:

  pull_request:

    types: [opened, synchronize, reopened]
 
jobs:

  review:

    runs-on: ubuntu-latest
 
    steps:

      # Step 1: Checkout PR code

      - name: Checkout code

        uses: actions/checkout@v3
 
      # Step 2: Set up Python environment

      - name: Set up Python

        uses: actions/setup-python@v4

        with:

          python-version: '3.10'
 
      # Step 3: Install required Python packages

      - name: Install dependencies

        run: |

          python -m pip install --upgrade pip

          pip install openai requests
 
      # Step 4: Run the AI code review script

      - name: Run AI code review

        run: python .github/scripts/review.py

        env:

          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

 